Add Symbols for JCasc Support
jenkinsci/tekton-client-plugin pull request #42
Opened 2020-09-16 04:46 UTC by waveywaves

2020-09-16 04:47 UTC, waveywaves commented
cc @oleg-nenashev

2020-09-22 09:24 UTC, oleg-nenashev requested changes
Please keep symbols specific to the Tekton Plugin

Also, when you have `DataboundSetter`, no need to have the same parameters in the `DataboundConstructor`.

2020-09-22 09:24 UTC, oleg-nenashev commented on src/main/java/org/waveywaves/jenkins/plugins/tekton/client/GlobalPluginConfiguration.java
> +@Symbol("Global")
Please keep a plugin-specific symbol, e.g. "tekton" or "tektonClient".

2020-09-22 09:24 UTC, oleg-nenashev commented on src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStep.java
> +@Symbol("createStep")
`tektonCreateStep` ?

2020-09-23 22:25 UTC, merged